/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NivelRouteImport } from './routes/nivel'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as GruposIndexRouteImport } from './routes/grupos.index'
import { Route as GruposGroupIdRouteImport } from './routes/grupos.$groupId'
import { Route as PerfilIndexRouteImport } from './routes/perfil.index'
import { Route as PerfilConfiguracoesRouteImport } from './routes/perfil.configuracoes'
import { Route as PerfilDepositarRouteImport } from './routes/perfil.depositar'
import { Route as PerfilKycRouteImport } from './routes/perfil.kyc'
import { Route as PerfilPagamentoRouteImport } from './routes/perfil.pagamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NivelRoute = NivelRouteImport.update({
  id: '/nivel',
  path: '/nivel',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposIndexRoute = GruposIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GruposRoute,
} as any)
const GruposGroupIdRoute = GruposGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => GruposRoute,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilConfiguracoesRoute = PerfilConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilDepositarRoute = PerfilDepositarRouteImport.update({
  id: '/depositar',
  path: '/depositar',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilKycRoute = PerfilKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilPagamentoRoute = PerfilPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => PerfilRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistente': typeof AssistenteRoute
  '/grupos': typeof GruposRouteWithChildren
  '/home': typeof HomeRoute
  '/nivel': typeof NivelRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/grupos/$groupId': typeof GruposGroupIdRoute
  '/perfil/configuracoes': typeof PerfilConfiguracoesRoute
  '/perfil/depositar': typeof PerfilDepositarRoute
  '/perfil/kyc': typeof PerfilKycRoute
  '/perfil/pagamento': typeof PerfilPagamentoRoute
  '/grupos/': typeof GruposIndexRoute
  '/perfil/': typeof PerfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistente': typeof AssistenteRoute
  '/home': typeof HomeRoute
  '/nivel': typeof NivelRoute
  '/grupos/$groupId': typeof GruposGroupIdRoute
  '/perfil/configuracoes': typeof PerfilConfiguracoesRoute
  '/perfil/depositar': typeof PerfilDepositarRoute
  '/perfil/kyc': typeof PerfilKycRoute
  '/perfil/pagamento': typeof PerfilPagamentoRoute
  '/grupos': typeof GruposIndexRoute
  '/perfil': typeof PerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistente': typeof AssistenteRoute
  '/grupos': typeof GruposRouteWithChildren
  '/home': typeof HomeRoute
  '/nivel': typeof NivelRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/grupos/$groupId': typeof GruposGroupIdRoute
  '/perfil/configuracoes': typeof PerfilConfiguracoesRoute
  '/perfil/depositar': typeof PerfilDepositarRoute
  '/perfil/kyc': typeof PerfilKycRoute
  '/perfil/pagamento': typeof PerfilPagamentoRoute
  '/grupos/': typeof GruposIndexRoute
  '/perfil/': typeof PerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistente'
    | '/grupos'
    | '/home'
    | '/nivel'
    | '/perfil'
    | '/grupos/$groupId'
    | '/perfil/configuracoes'
    | '/perfil/depositar'
    | '/perfil/kyc'
    | '/perfil/pagamento'
    | '/grupos/'
    | '/perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistente'
    | '/home'
    | '/nivel'
    | '/grupos/$groupId'
    | '/perfil/configuracoes'
    | '/perfil/depositar'
    | '/perfil/kyc'
    | '/perfil/pagamento'
    | '/grupos'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistente'
    | '/grupos'
    | '/home'
    | '/nivel'
    | '/perfil'
    | '/grupos/$groupId'
    | '/perfil/configuracoes'
    | '/perfil/depositar'
    | '/perfil/kyc'
    | '/perfil/pagamento'
    | '/grupos/'
    | '/perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssistenteRoute: typeof AssistenteRoute
  GruposRoute: typeof GruposRouteWithChildren
  HomeRoute: typeof HomeRoute
  NivelRoute: typeof NivelRoute
  PerfilRoute: typeof PerfilRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nivel': {
      id: '/nivel'
      path: '/nivel'
      fullPath: '/nivel'
      preLoaderRoute: typeof NivelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos/': {
      id: '/grupos/'
      path: '/'
      fullPath: '/grupos/'
      preLoaderRoute: typeof GruposIndexRouteImport
      parentRoute: typeof GruposRoute
    }
    '/grupos/$groupId': {
      id: '/grupos/$groupId'
      path: '/$groupId'
      fullPath: '/grupos/$groupId'
      preLoaderRoute: typeof GruposGroupIdRouteImport
      parentRoute: typeof GruposRoute
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/configuracoes': {
      id: '/perfil/configuracoes'
      path: '/configuracoes'
      fullPath: '/perfil/configuracoes'
      preLoaderRoute: typeof PerfilConfiguracoesRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/depositar': {
      id: '/perfil/depositar'
      path: '/depositar'
      fullPath: '/perfil/depositar'
      preLoaderRoute: typeof PerfilDepositarRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/kyc': {
      id: '/perfil/kyc'
      path: '/kyc'
      fullPath: '/perfil/kyc'
      preLoaderRoute: typeof PerfilKycRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/pagamento': {
      id: '/perfil/pagamento'
      path: '/pagamento'
      fullPath: '/perfil/pagamento'
      preLoaderRoute: typeof PerfilPagamentoRouteImport
      parentRoute: typeof PerfilRoute
    }
  }
}

interface GruposRouteChildren {
  GruposGroupIdRoute: typeof GruposGroupIdRoute
  GruposIndexRoute: typeof GruposIndexRoute
}

const GruposRouteChildren: GruposRouteChildren = {
  GruposGroupIdRoute: GruposGroupIdRoute,
  GruposIndexRoute: GruposIndexRoute,
}

const GruposRouteWithChildren =
  GruposRoute._addFileChildren(GruposRouteChildren)

interface PerfilRouteChildren {
  PerfilConfiguracoesRoute: typeof PerfilConfiguracoesRoute
  PerfilDepositarRoute: typeof PerfilDepositarRoute
  PerfilKycRoute: typeof PerfilKycRoute
  PerfilPagamentoRoute: typeof PerfilPagamentoRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilConfiguracoesRoute: PerfilConfiguracoesRoute,
  PerfilDepositarRoute: PerfilDepositarRoute,
  PerfilKycRoute: PerfilKycRoute,
  PerfilPagamentoRoute: PerfilPagamentoRoute,
  PerfilIndexRoute: PerfilIndexRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssistenteRoute: AssistenteRoute,
  GruposRoute: GruposRouteWithChildren,
  HomeRoute: HomeRoute,
  NivelRoute: NivelRoute,
  PerfilRoute: PerfilRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
