/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NivelRouteImport } from './routes/nivel'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as CarteiraIndexRouteImport } from './routes/carteira.index'
import { Route as CarteiraDepositarRouteImport } from './routes/carteira.depositar'
import { Route as PerfilIndexRouteImport } from './routes/perfil.index'
import { Route as PerfilConfiguracoesRouteImport } from './routes/perfil.configuracoes'
import { Route as PerfilKycRouteImport } from './routes/perfil.kyc'
import { Route as CarteiraMetodoMethodRouteImport } from './routes/carteira.metodo.$method'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NivelRoute = NivelRouteImport.update({
  id: '/nivel',
  path: '/nivel',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraIndexRoute = CarteiraIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarteiraRoute,
} as any)
const CarteiraDepositarRoute = CarteiraDepositarRouteImport.update({
  id: '/depositar',
  path: '/depositar',
  getParentRoute: () => CarteiraRoute,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilConfiguracoesRoute = PerfilConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilKycRoute = PerfilKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => PerfilRoute,
} as any)
const CarteiraMetodoMethodRoute = CarteiraMetodoMethodRouteImport.update({
  id: '/metodo/$method',
  path: '/metodo/$method',
  getParentRoute: () => CarteiraRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/carteira': typeof CarteiraRouteWithChildren
  '/home': typeof HomeRoute
  '/nivel': typeof NivelRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/carteira/depositar': typeof CarteiraDepositarRoute
  '/perfil/configuracoes': typeof PerfilConfiguracoesRoute
  '/perfil/kyc': typeof PerfilKycRoute
  '/carteira/': typeof CarteiraIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/carteira/metodo/$method': typeof CarteiraMetodoMethodRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/home': typeof HomeRoute
  '/nivel': typeof NivelRoute
  '/carteira/depositar': typeof CarteiraDepositarRoute
  '/perfil/configuracoes': typeof PerfilConfiguracoesRoute
  '/perfil/kyc': typeof PerfilKycRoute
  '/carteira': typeof CarteiraIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/carteira/metodo/$method': typeof CarteiraMetodoMethodRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/carteira': typeof CarteiraRouteWithChildren
  '/home': typeof HomeRoute
  '/nivel': typeof NivelRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/carteira/depositar': typeof CarteiraDepositarRoute
  '/perfil/configuracoes': typeof PerfilConfiguracoesRoute
  '/perfil/kyc': typeof PerfilKycRoute
  '/carteira/': typeof CarteiraIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/carteira/metodo/$method': typeof CarteiraMetodoMethodRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/carteira'
    | '/home'
    | '/nivel'
    | '/perfil'
    | '/carteira/depositar'
    | '/perfil/configuracoes'
    | '/perfil/kyc'
    | '/carteira/'
    | '/perfil/'
    | '/carteira/metodo/$method'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/home'
    | '/nivel'
    | '/carteira/depositar'
    | '/perfil/configuracoes'
    | '/perfil/kyc'
    | '/carteira'
    | '/perfil'
    | '/carteira/metodo/$method'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/carteira'
    | '/home'
    | '/nivel'
    | '/perfil'
    | '/carteira/depositar'
    | '/perfil/configuracoes'
    | '/perfil/kyc'
    | '/carteira/'
    | '/perfil/'
    | '/carteira/metodo/$method'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  CarteiraRoute: typeof CarteiraRouteWithChildren
  HomeRoute: typeof HomeRoute
  NivelRoute: typeof NivelRoute
  PerfilRoute: typeof PerfilRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nivel': {
      id: '/nivel'
      path: '/nivel'
      fullPath: '/nivel'
      preLoaderRoute: typeof NivelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira/': {
      id: '/carteira/'
      path: '/'
      fullPath: '/carteira/'
      preLoaderRoute: typeof CarteiraIndexRouteImport
      parentRoute: typeof CarteiraRoute
    }
    '/carteira/depositar': {
      id: '/carteira/depositar'
      path: '/depositar'
      fullPath: '/carteira/depositar'
      preLoaderRoute: typeof CarteiraDepositarRouteImport
      parentRoute: typeof CarteiraRoute
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/configuracoes': {
      id: '/perfil/configuracoes'
      path: '/configuracoes'
      fullPath: '/perfil/configuracoes'
      preLoaderRoute: typeof PerfilConfiguracoesRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/kyc': {
      id: '/perfil/kyc'
      path: '/kyc'
      fullPath: '/perfil/kyc'
      preLoaderRoute: typeof PerfilKycRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/carteira/metodo/$method': {
      id: '/carteira/metodo/$method'
      path: '/metodo/$method'
      fullPath: '/carteira/metodo/$method'
      preLoaderRoute: typeof CarteiraMetodoMethodRouteImport
      parentRoute: typeof CarteiraRoute
    }
  }
}

interface CarteiraRouteChildren {
  CarteiraDepositarRoute: typeof CarteiraDepositarRoute
  CarteiraIndexRoute: typeof CarteiraIndexRoute
  CarteiraMetodoMethodRoute: typeof CarteiraMetodoMethodRoute
}

const CarteiraRouteChildren: CarteiraRouteChildren = {
  CarteiraDepositarRoute: CarteiraDepositarRoute,
  CarteiraIndexRoute: CarteiraIndexRoute,
  CarteiraMetodoMethodRoute: CarteiraMetodoMethodRoute,
}

const CarteiraRouteWithChildren = CarteiraRoute._addFileChildren(
  CarteiraRouteChildren,
)

interface PerfilRouteChildren {
  PerfilConfiguracoesRoute: typeof PerfilConfiguracoesRoute
  PerfilKycRoute: typeof PerfilKycRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilConfiguracoesRoute: PerfilConfiguracoesRoute,
  PerfilKycRoute: PerfilKycRoute,
  PerfilIndexRoute: PerfilIndexRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  CarteiraRoute: CarteiraRouteWithChildren,
  HomeRoute: HomeRoute,
  NivelRoute: NivelRoute,
  PerfilRoute: PerfilRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
